# Generated by Django 3.2.12 on 2022-03-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
